# Generated by Django 5.2 on 2025-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VtasApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total',
            new_name='acta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='id',
            new_name='id_vta',
        ),
        migrations.AddField(
            model_name='venta',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
